#!/bin/sh


# Script Environment Variables
# -------------------------------------------------------------------------------------
# SYNOPKG_PKGNAME               =   Package identify which is defined in INFO
# SYNOPKG_PKGVER                =   Package version which is defined in INFO
# SYNOPKG_PKGDEST               =   Package destination path
#                                   /volume[x]/@appstore/[Package Name]
# SYNOPKG_TEMP_UPGRADE_FOLDER   =   Temporary upgrade folder
#                                   /volume1/@tmp/synopkg.tmp/[Package Name]
# -------------------------------------------------------------------------------------


# Important Paths, soft links and variables
# -------------------------------------------------------------------------------------
# DSM WebGUI folder
# /usr/syno/synoman/webman/3rdparty/[Package Name] -> /var/packages/[Package Name]/target
WEBGUI_FOLDER="/usr/syno/synoman/webman/3rdparty/${SYNOPKG_PKGNAME}"

# Soft link
# /var/packages/[Package Name]/target -> /volume1/@appstore/[Package Name]
PACKAGE_FOLDER="/var/packages/${SYNOPKG_PKGNAME}/target/ui"

# erstelle benötigte Symlinks:
[ ! -h /usr/syno/synoman/webman/3rdparty/synOTR/app/libARMv7l/libcurl.so.3 ] && ln -s /usr/syno/synoman/webman/3rdparty/synOTR/app/libARMv7l/libcurl.so.4 /usr/syno/synoman/webman/3rdparty/synOTR/app/libARMv7l/libcurl.so.3
[ ! -h /usr/syno/synoman/webman/3rdparty/synOTR/app/libARMv7l/libidn2.so.0 ] && ln -s /usr/syno/synoman/webman/3rdparty/synOTR/app/libARMv7l/libidn2.so.0.1.4 /usr/syno/synoman/webman/3rdparty/synOTR/app/libARMv7l/libidn2.so.0
[ ! -h /usr/syno/synoman/webman/3rdparty/synOTR/app/libARMv7l/libpsl.so.5 ] && ln -s /usr/syno/synoman/webman/3rdparty/synOTR/app/libARMv7l/libpsl.so.5.1.1 /usr/syno/synoman/webman/3rdparty/synOTR/app/libARMv7l/libpsl.so.5
[ ! -h /usr/syno/synoman/webman/3rdparty/synOTR/app/libARMv7l/libunistring.so.0 ] && ln -s /usr/syno/synoman/webman/3rdparty/synOTR/app/libARMv7l/libunistring.so.0.1.2 /usr/syno/synoman/webman/3rdparty/synOTR/app/libARMv7l/libunistring.so.0

# Timestamp - Formatting the Timestamp to terminate log entries
TIMESTAMP=$(date +%Y-%m-%d%t%H:%M:%S)
# -------------------------------------------------------------------------------------

# Action...
# -------------------------------------------------------------------------------------

# DSM6:
# LOG="/var/packages/${SYNOPKG_PKGNAME}/log"
# ln -s $SYNOPKG_PKGDEST /usr/syno/synoman/webman/3rdparty/synOTR
# date +'%c installed' >> $LOG

 exit 0